spec:
  imagePullSecrets: acr-secret

config:
  connectionStrings:
    postgres: "{{ POSTGRES_CONNECTION_STRING }}"
    storageAccount: "{{ STORAGE_ACCOUNT_CONNECTION_STRING }}"
  jwt:
    audience: "http://cms.api.local.development.tlis.sk"
    authority: "https://tlis.eu.auth0.com"
    requireHttpsMetadata: false
  serviceUrls:
    storageAccount: "{{ STORAGE_ACCOUNT }}"