spec:
  imagePullSecrets: acr-secret

config:
  connectionStrings:
    postgres: "{{ POSTGRES_CONNECTION_STRING }}"
    storageAccount: "{{ STORAGE_ACCOUNT_CONNECTION_STRING }}"
  jwt:
    audience: "http://cms.api.local.development.tlis.sk"
    authority: "https://tlis.eu.auth0.com"
  serviceUrls:
    storageAccount: "{{ STORAGE_ACCOUNT }}"
  auth0:
    domain: "{{ AUTH0_DOMAIN }}}"
    clientId: "{{ AUTH0_CLIENT_ID }}"
    clientSecret: "{{ AUTH0_CLIENT_SECRET }}"